#Creator Reed Ceniviva 12/1/16
#CS265 Assignment 4 Bank Accounts
#I heavily used the example file provide to make this makefile


.PHONY : build view clean

build :
			chmod +x accounts

view :
			@\less accounts

clean :
			@\rm *.pyv
